#Q1) PRINT YOUR NAME ?
print('radha krishna')  
#       or 
print("radha krishna")

## Q2)  PRINT THE NAMES OF YOUR FAMILY MEMBERS ?
print("radha")
print("krishna")
print("shiv")

## Q3) PRINT "TWINKLE TWINKLE LITTER STAR POEM" ?
print("""Twinkle twinkle little star.
How I wonder what you are.
Up above the world so high.
Like a diamond in the sky.
Twinkle twinkle little star.
How I wonder what you are.

Twinkle twinkle little star.
How I wonder what you are.
Up above the world so high.
Like a diamond in the sky.
Twinkle twinkle little star.
How I wonder what you are """)

# QUESTION BASED ON COMMENTS 
# Q) EXPLAIN ALL THE LINE OF CODE IN PRINT FUNCTION WHY USE SINGLE QUOTES OR DOUBLE QUOTES AND TRIPLE QUOTES?
""" Q1) solution = we use single or double quotes in first question because it is single
display output. """